- _config.yml
- _layouts/default.html
- index.md
We can now host our own helm repo in github and use our releases as the artifacts rather than storing a helm chart archive in a repo
> Add Helm Repo web page

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
Using the tmp directory means that the system can wipe out falcon information. This PR also updates the falconstore to be located where Linux would typically expect application data to be stored.
> Don't use /tmp to store falcon information

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.yaml
The daemonset should have configurable tolerations, in addition to being runnable on master nodes.
> [helm] configurable tolerations

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
Setting `serviceAccountName` is necessary when using PodSecurityPolicies that generally don't allow running privileged pods. In this case, a separate service account must be created and associated with a privileged PodSecurityPolicy.
This adds a small template change to allow setting this value from `.Vaules.node.daemonset.serviceAccountName`.
> Add support for setting serviceAccountName

- helm-charts/falcon-sensor/Chart.yaml
Addressing 
```
Error: chart requires kubeVersion: >1.15.0-0 <1.22.0-0 which is incompatible with Kubernetes v1.22.1-3+e6976ed80e19e1
```
> Kubernetes 1.22 should be supported

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
This is related to https://github.com/CrowdStrike/falcon-helm/issues/92
The property, as defined, expects an object-type value. However, the Pod spec expects an array-type value for the "imagePullSecrets" property. Source: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret
In the current state, if we pass an object to node.image.pullSecrets, we pass schema validation but receive an error from Kubernetes:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.imagePullSecrets): invalid type for io.k8s.api.core.v1.PodSpec.imagePullSecrets: got "map", expected "array"
```
Conversely, if we pass an array, we fail schema …
> Fixes an issue with the node.image.pullSecrets property

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/clusterrolebinding.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_scc.yaml
- helm-charts/falcon-sensor/templates/serviceaccount.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
- [Fix] the hardcoded serviceAccountName in the daemonset
- [Fix] the hardcoded serviceAccountName in the clusterrolebinding
- [Fix] the hardcoded serviceAccountName in the SecurityContextConstraints
- [Fix] the hardcoded serviceAccountName in the ServiceAccount
- [Update] the values schema to support the serviceAccountName at root of values
- [Update] the ServiceAccount creation based on values (default : true as the account was created before but not used)
- [Add] the usage of the serviceAccountName for the injector
- [Add] Values : add the custom value for the serviceAccountName
Those changes allows the Falcon Container to be deployed on GKE cluster with Workload Identity (config actually recommended and not yet enforced on GCP side) …
> Enable and Allow the customization of serviceAccountName

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
Fixes error with the injector replicaset where it would fail to create pods with the following error:
> Error creating: Internal error occurred: failed calling webhook "falcon-sensor-injector.falcon-system.svc": failed to call webhook: Post "https://falcon-sensor-injector.falcon-system.svc:443/mutate?timeout=30s": no endpoints available for service "falcon-sensor-injector"
Also moves the anti-affinity on masters for node scheduling to soft rule / preference to allow scheduling in small / single node clusters where all nodes have master role.
> Fix namespace selector in webhook to exclude release namespace + move master anti-affinity to preference

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
Ensures resources in kube-system/public namespaces are not targeted by mutatingwebhook and failing if falcon-container injector service is unavailable.
> exclude kube-system and kube-public from webhook config

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/clusterrolebinding.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/templates/node_scc.yaml
- helm-charts/falcon-sensor/templates/serviceaccount.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
This commit supports annotations which will allow the Falcon container sensor to utilize both GCP [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to) and (probably) AWS OIDC. https://github.com/CrowdStrike/falcon-helm/pull/91 allowed for the renaming of service accounts however annotations are required.
> Support service account annotations

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/values.yaml
There are scenarios, albeit few and far between, where the daemonset pod would get scheduled on nodes that were not supported (or intended to deployed to) e.g. Fargate nodes.
This change also allows for complete control of the tolerations set on the daemonset pods (excluding those set by the K8s API itself)
> fix: tolerate taints on control-plane nodes only (by default)

- .github/workflows/helm-release.yml
- .github/workflows/helm-test.yaml
- Auto-release helm charts on chart version change after merge into main
- Only run when there are changes in `helm-charts` dir
> Update GH actions

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
Hi,
This PR allows to configure the number of replicas for the webhook backend. The default value is 1 as before, but it's important, especially in production clusters, to have multiple replicas in order to be compliant with best practices https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#availability
Please could you review it?
Thanks
> Add webhook replicas in values

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/container_secret.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
In some deployment cases, secrets can be provisioned/updated by another method - this update allow to customize Falcon container secret name.
> Falcon Container - Allow customization of secret name

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
This adds nodeAffinity for the DS as an optional configuration. Allowing one to set additional node selections e.g. processor type:
```yaml
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/arch
operator: In
values:
- amd64
```
Also, I removed an unusable falconctl and moved nameOverride and fullnameOverride to the root of the values since it was nested inside of the daemonset options and not used there.
> Add nodeAffinity. Fix a few values

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
This PR enable an initContainer for GCP GKE setup in order to avoid issue with workload identity whenever a node pool is scaled down to 0 and then scaled up to > 0. Added also toleration for deployment setup.
> GCP workload identity changes for deployment

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/templates/container_psp.yaml
- Only deploy container sensor psp for kube version < 25
- Add notes to configure Pod Security Standards to Kubernetes 1.25+
> PSP and Pod Security Standards handling

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
Presently, setting the PriorityClass for the DaemonSet Pods is impossible. Pods may be evicted or not be scheduled at all in case of resource shortage on the worker nodes.
This PR enables the possibility of setting a PriorityClass, such as system-node-critical, via the Pod template and is an updated version of #150, excluding the aspects of resource requests and limits.
> [Feature] Add possibilty to the PriorityClass for the DaemonSet

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- In some cases when the operator was not deployed correctly, Kubernetes would create the falconstore file as a directory. This adds the capability for the initContainer to fix that by deleting falconstore if it is a directory when it should be a file.
> fix: ensure falconstore is a file when initContainer runs

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
Relates to https://github.com/CrowdStrike/falcon-operator/pull/332
The current behavior of this chart is to generate the FALCONCTL_OPT_BACKEND environment variable (via configmap) when falcon.backend is set (as it is, by default), regardless of whether the node or container sensor is being deployed.
This variable and corresponding command argument causes a fatal error in version 6.51+ of the container sensor.
> breaking fix: move falcon.backend to node.backend

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/values.schema.json
Internal request was raised to throw an error if falcon.backend is set, so that customers can identify the change earlier and adjust to node.backend.
> fix: throw validation error if falcon.backend is set

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/values.schema.json
This PR enables setting maxUnavailable as percentage.
[DaemonSetSpec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec) clearly defines the  maxUnavailable field as IntOrString
> Enable setting maxUnavailable as percentage

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- GCOS is now supported as a node type for GKE deployments
- OpenShift support is now deprecated as OpenShift users should use the certified operator to maintain support with Red Hat
> fix: supported distros in README

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/templates/node_secret_cleanup.yaml
Fixing the issue by adding a dedicated pull-secret for the post-delete helm's hook.
When the cleanup daemonset is deployed, the pod can't be deployed due to the pull secret already deleted by helm (we are in the post-delete stage at that time).
```
daemonset/falcon-helm-falcon-sensor-node-cleanup   Created pod: falcon-helm-falcon-sensor-node-cleanup-tckrc
pod/falcon-helm-falcon-sensor-node-cleanup-tckrc   Successfully assigned falcon-system/falcon-helm-falcon-sensor-node-cleanup-tckrc to workernode
daemonset/falcon-helm-falcon-sensor-node-cleanup   Created pod: falcon-helm-falcon-sensor-node-cleanup-t6blh
pod/falcon-helm-falcon-sensor-node-cleanup-t6blh   Successfully assigned falcon-system/falcon-helm-falcon-sensor-node-cleanup-t6blh to workernode …
```
> fixing cleaning issue when using registryConfigJSON

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/configmap.yaml
Creating the `falcon-sensor` with the following configuration mangles the proxy settings:
```yaml
falcon:
cid: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-AA
apd: false
aph: hostname
app: 1234
```
Resulting ConfigMap values:
```yaml
data:
FALCONCTL_OPT_CID: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-AA
FALCONCTL_OPT_APH: "hostname"
FALCONCTL_OPT_APP: "1234"
FALCONCTL_OPT_TRACE: "none"
FALCONCTL_OPT_BACKEND: "kernel"
```
After this fix:
```yaml
data:
FALCONCTL_OPT_CID: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-AA
FALCONCTL_OPT_APD: "false"
FALCONCTL_OPT_APH: "hostname"
FALCONCTL_OPT_APP: "1234"
FALCONCTL_OPT_TRACE: "none"
FALCONCTL_OPT_BACKEND: "kernel"
```
APD needs to be "false" when enabling the proxy (disable = false, so enable), so this value is _only_ needed when it's false.
The admission controller helm chart …
> Fix: sensor: APD ConfigMap value is missing when false

- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/templates/clusterrole.yaml
This is required to allow OpenShift cluster name to be read by KAC pod
> allow read access to deployments

- helm-charts/cs-k8s-protection-agent/Chart.yaml
- helm-charts/cs-k8s-protection-agent/templates/configmap.yaml
The `AGENT_CLIENT_ID` and `AGENT_CLIENT_SECRET` are used to create a secret object, which in turn are set as environmental variables for the container by referencing the secret. There is no need to set the `AGENT_CLIENT_ID` environmental variable by adding it again to the configmap.
> Remove AGENT_CLIENT_ID from the KPA configmap

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/node_priorityclass.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
fixes: #230 
Allows for the user to specify a preexisting PriorityClass by opting out of the creation of one in this Chart.
> fix(falcon-sensor): allow for preexisting PriorityClass

- helm-charts/cs-k8s-protection-agent/Chart.yaml
- helm-charts/cs-k8s-protection-agent/values.schema.json
Apply clientID validation logic only when existingSecret is empty. We are using an `existingSecret` and not hardcoding the `clientID` and `clientSecret` in `values.yaml`. Right now, `clientID` validation is performed even if the `existingSecret` is defined. As a result, this is breaking our deployment.
> KPA: Apply clientID validation logic only when existingSecret is empty

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/_helpers.tpl
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/values.yaml
- only apply resources if GKE autopilot or enabled explicitly
- change ephemeral storage to 100Mi
> fix: sensor resource handling

- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/templates/clusterrole.yaml
For dry-run mode, falcon-kac needs read permissions on the resources it validates as admission controller webhook
> add read permissions for resources that are monitored by KAC

- helm-charts/cs-k8s-protection-agent/Chart.yaml
- helm-charts/cs-k8s-protection-agent/templates/deployment.yaml
- helm-charts/cs-k8s-protection-agent/templates/docker-secret.yaml
in deployment.yaml line 32 : the secret name should end with `-registryconfigjson`
```
- name: {{ include "cs-k8s-protection-agent.fullname" . }}-regsecret-registryconfigjson
```
This is fixing the secret name
> fix(kpa): update regsecret's name when registryConfigJSON is used

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
If a user removes `priorityClassCreate` from the values file entirely, the default action should not be to attempt to create a priorityClass of a given `priorityClassName`.  
In my opinion/experience, if the user is using the default helm values file as a guide and has indicated the name of a priority-class to use but has deleted the directive to create a priority class by that name, the intended action is to *not* try to create that priority-class.
> Default priorityClassCreate to false

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/values.yaml
if not forced to empty string, helm is taking the variable as an interface{}
without the default value : 
```
Error: template: falcon-sensor/templates/container_secret.yaml:15:30: executing "falcon-sensor/templates/container_secret.yaml" at <.Values.container.image.pullSecrets.namespaces>: wrong type for value; expected string; got interface {}
helm.go:84: [debug] template: falcon-sensor/templates/container_secret.yaml:15:30: executing "falcon-sensor/templates/container_secret.yaml" at <.Values.container.image.pullSecrets.namespaces>: wrong type for value; expected string; got interface {}
```
> Forcing the param namespaces to be a default empty string

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/templates/node_secret_cleanup.yaml
- helm-charts/falcon-sensor/templates/serviceaccount_cleanup.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
fixes: #278 
Allows for helm hooks to be optionally toggled off, the default behavior is that they are enabled for backward compatibility.
> feat(falcon-sensor): allow helm hook manifests to be disabled

- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/templates/resourcequota.yaml
- helm-charts/falcon-kac/values.schema.json
- helm-charts/falcon-kac/values.yaml
Hi team,
I want to parameterise `spec.hard.pods` in `ResourceQuota` object. This is useful when falcon-kac is deployed on to namespace where there are existing deployments that take up pods quota with `PriorityClass=system-cluster-critical` ( for example: api-server in kube-system namespace
Fixes: https://github.com/CrowdStrike/falcon-helm/issues/241
> Parameterise the hard limit on pods in ResourceQuota object

- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/templates/deployment_webhook.yaml
- helm-charts/falcon-kac/values.schema.json
- helm-charts/falcon-kac/values.yaml
This will allow falcon-kac to be used on multi-arch clusters, as long as there is a amd64 node available.
I've tested this is working on a fresh EKS cluster with Karpenter - it brought up a c7i.large instance alongside the m7g.large instances that were there already
> Allow setting nodeSelector and affinity for falcon-kac

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/README.md
- helm-charts/falcon-image-analyzer/ci/cid-values.yaml
- helm-charts/falcon-image-analyzer/templates/daemonset.yaml
- helm-charts/falcon-image-analyzer/templates/deployment.yaml
- helm-charts/falcon-image-analyzer/values.schema.json
- helm-charts/falcon-image-analyzer/values.yaml
- Require either daemonset or deployment to be enabled
- Disable sidecar injection
- Set default affinity settings
> feat: set securityContext for deployments

- helm-charts/falcon-integration-gateway/Chart.yaml
- helm-charts/falcon-integration-gateway/templates/configmap.yaml
> fix(fig): use the default boolean values from values.yaml

- helm-charts/falcon-integration-gateway/Chart.yaml
- helm-charts/falcon-integration-gateway/README.md
Doc updates to match recent FIG changes
> docs(fig): update readme to reflect recent changes

- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/templates/deployment_webhook.yaml
- helm-charts/falcon-kac/values.schema.json
- helm-charts/falcon-kac/values.yaml
This is creating a prerelease build of version `1.2.0-rc.1`. Ideally, this would be done from the working branch, but limitations in the [chart releaser tool](https://github.com/helm/chart-releaser) prevent this.
> wip: add cluster visibility to falcon-kac

- helm-charts/falcon-self-hosted-registry-assessment/Chart.yaml
- helm-charts/falcon-self-hosted-registry-assessment/README.md
- helm-charts/falcon-self-hosted-registry-assessment/values.yaml
SHRA now supports direct ECR access and assuming a role to access ECR
> SHRA-1.2 release

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/README.md
- helm-charts/falcon-image-analyzer/templates/daemonset.yaml
- helm-charts/falcon-image-analyzer/templates/deployment.yaml
- helm-charts/falcon-image-analyzer/values.yaml
v1.1.11 helm updates for hostNetwork
> v1.1.11 helm updates for hostNetwork

- helm-charts/falcon-sensor/templates/clusterrole.yaml
- helm-charts/falcon-sensor/templates/clusterrolebinding.yaml
partial output of 
`kubectl get clusterrole falcon-falcon-sensor-access-role  -n falcon-system -o yaml`
```
app.kubernetes.io/component: kernel_sensor
app.kubernetes.io/instance: falcon
rules:
- apiGroups:
- ""
resources:
- secrets
- pods
- services
- nodes
- daemonsets
- replicasets
- deployments
- jobs
- ingresses
- cronjobs
- persistentvolumes
verbs:
- get
- watch
- list
```
> sensor | clusterrole | add resources and verbs

- helm-charts/falcon-sensor/templates/clusterrole.yaml
- helm-charts/falcon-sensor/templates/clusterrolebinding.yaml
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
Currently, we are running in the hostnetwork.
Without ClusterFirstWithHostNet DNS configuration, we can't query the k8s cluster dns server (and its resources)
> cdp: set ClusterFirstWithHostNet for node sensor

- helm-charts/falcon-kac/templates/deployment_webhook.yaml
- helm-charts/falcon-kac/values.schema.json
- helm-charts/falcon-kac/values.yaml
This PR introduces support for running KAC on hostNetwork and setting of dnsPolicy which is needed when some scenarios such as when custom CNI's are in use and control plane nodes are not be able to initiate network connections to pods.
Additionally this change adds support for configuring the watcher port and fixes missing webhookPort from being passed to the container client.
> Add support for running KAC on hostNetwork

- helm-charts/falcon-sensor/templates/daemonset.yaml
tldr:
sensor is running as UID 0.
cdp module is running in a user namespace => cdp can't access the  volumes  created by k8s
`"failed to get orchestration get in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: permission denied"`
issue also referred here https://github.com/kubernetes-sigs/external-dns/pull/1185
> cdp: add fsGroup as nobody group

- .github/workflows/helm-release.yml
This adds a manual way to deploy releases outside of PRs. This will be used for release candidates, testing release automation, etc.
> Add manual release github action

- helm-charts/aspm-relay/templates/role.yaml
This PR fixes a typo in role.yaml that causes exec method to not work properly.
> ASPM Relay - fix exec

- helm-charts/aspm-relay/templates/deployment.yaml
Pod labels were not passed correctly as an env, this PR fixes it.
> ASPM Relay: Fix pod labels json

- helm-charts/falcon-sensor/templates/_helpers.tpl
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
- Add labels for troubleshooting the primary and cleanup daemonsets for AutoPilot.
- Set configMap name to be a static value when Autopilot is enabled
> Ensure configurations work with WorkloadAllowlist

- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/templates/_helpers.tpl
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/templates/node_priorityclass.yaml
- helm-charts/falcon-sensor/templates/node_secret.yaml
- helm-charts/falcon-sensor/templates/node_secret_cleanup.yaml
- helm-charts/falcon-sensor/templates/serviceaccount.yaml
- helm-charts/falcon-sensor/templates/serviceaccount_cleanup.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
Setting `node.cleanupOnly` to `true` will run the cleanup daemonset when `node.enabled`.  The Daemonset will run indefinitely and only be removed during a helm uninstall to ensure cleanup runs on all nodes.
> Add ability to run the cleanup Daemonset only

- helm-charts/falcon-sensor/templates/_helpers.tpl
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/container_secret.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/templates/node_secret.yaml
- helm-charts/falcon-sensor/templates/node_secret_cleanup.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
These new helper functions to check for global values is to support changes that will be included in the unified falcon helm chart. These global values are values that can be shared across multiple helm charts when deployed from a parent helm chart.
> feat(falcon-sensor): add global values support for falcon-sensor

- helm-charts/falcon-image-analyzer/templates/_helpers.tpl
- helm-charts/falcon-image-analyzer/templates/configmap.yaml
- helm-charts/falcon-image-analyzer/templates/daemonset.yaml
- helm-charts/falcon-image-analyzer/templates/deployment.yaml
- helm-charts/falcon-image-analyzer/templates/docker-secret.yaml
- helm-charts/falcon-image-analyzer/templates/secret.yaml
- helm-charts/falcon-image-analyzer/values.schema.json
- helm-charts/falcon-image-analyzer/values.yaml
These new helper functions to check for global values is to support changes that will be included in the unified falcon helm chart. These global values are values that can be shared across multiple helm charts when deployed from a parent helm chart.
> feat(falcon-iar): add global values support for falcon-image-analyzer
