- Makefile
- README.md
- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/NOTES.txt
- helm-charts/falcon-sensor/values.yaml
- Add install and release targets for Helm
- Add README notes on installation
- Update chart notes
- Add more securityContext configuration values
- Update Chart to use GitHub Falcon image
> Various Helm Chart Updates

- .github/config/ct.yaml
- .github/workflows/helm-test.yaml
Needed to actually get the CI/CD working correctly
> Add helm CI/CD config

- .github/config/ct.yaml
- .github/workflows/helm-test.yaml
- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/ci/cid-values.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.yaml
- tests/ct.yaml
- Ensure sensor is installed on all nodes including master nodes
- Ensure sensor is privileged so that it can run in OCP
> Fix various issues running on OCP

- README.md
- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.yaml
- This enhancement is allows for future changes to add additional components like the installing both a container sensor and node sensor.
> Update helm templates to configure and apply deamonset for nodes only

- README.md
Update readme to mention that the sensor image should match the node operating system.
> Remove duplicate instruction and add instruction about node operating system

- Makefile
- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/app-readme.md
- helm-charts/falcon-sensor/questions.yaml
- helm-charts/falcon-sensor/templates/NOTES.txt
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.yaml
- Don't allow customization of securityContext settings in helm
- Update questions grouping
- Remove legacy rancher labels and use annotations
- Add Chart level README and app-readme for Rancher deployment
- Remove namespace customization and update instructions to create namespace
- Add dependencies
> Various updates and fixes

- README.md
- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
Let's see if some of these changes fix some of the formatting issues in ArtifactHub
> Update Readme's with installation instructions

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
> Update MD table for Node Configuration

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
Changes were missed for previous PR #15
> Fix missing namespace changes

- index.yaml
Previous releases were missing due to a typo.
> Add previous releases to index.yaml

- README.md
Finally got to be able to test deploying a helm chart to EKS and GKE.
> Update supported Kubernetes Distros

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.yaml
This is required if hosting the falcon image in a private registry.
> Expose the option to set imagePullSecrets on the daemonset

- README.md
- docs/developer_guide.md
- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- Start filling out the developer guide
- Fix some minor typos in the main readme
> More documentation updates

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/app-readme.md
Update to readme after marketing review
> Update Chart app-readme.md for Marketplace listing

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/container_deployment.yaml
- helm-charts/falcon-sensor/templates/container_secret.yaml
- helm-charts/falcon-sensor/templates/container_service.yaml
- helm-charts/falcon-sensor/templates/container_webhook.yaml
- helm-charts/falcon-sensor/values.yaml
- Don't allow custom certs for the injector
- Remove runasuser/runasgroup as this breaks on OpenShift
- Update configmap with container entries
- Disable pull secret creation unless configured
- Autogenerate certs for the injector
> Update Container Sensor configuration

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_clusterrole.yaml
- helm-charts/falcon-sensor/templates/container_clusterrolebinding.yaml
- helm-charts/falcon-sensor/templates/container_webhook.yaml
- helm-charts/falcon-sensor/values.yaml
- Fix certificate generation
- Add customizable certificate expiration
- Fix name generation for clusterrole and clusterrolebinding
> More container sensor fixes

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_scc.yaml
- Update kube labeling
- Update Helm labeling
- Add SCC for node access
> Daemonset updates

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_clusterrole.yaml
- helm-charts/falcon-sensor/templates/container_clusterrolebinding.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/container_secret.yaml
- helm-charts/falcon-sensor/templates/container_service.yaml
- Update labeling to bring in line to latest helm, crowdstrike, kubernetes labels
- Remove add non-namespaced webhook key
> Container updates

- helm-charts/falcon-sensor/Chart.yaml
Needed to meet new Rancher requirements. Plus it would be a good thing to have in general.
> Add kubeVersion in Chart.yml

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_clusterrole.yaml
- helm-charts/falcon-sensor/templates/container_clusterrolebinding.yaml
- helm-charts/falcon-sensor/templates/container_scc.yaml
- Add SCC for OpenShift
- Enable SCC in roles
- Allow NS to pull image from container NS
> Add perms to container sensor implementation

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_clusterrole.yaml
- helm-charts/falcon-sensor/templates/container_clusterrolebinding.yaml
- helm-charts/falcon-sensor/templates/container_psp.yaml
- helm-charts/falcon-sensor/templates/container_scc.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_psp.yaml
- helm-charts/falcon-sensor/templates/node_scc.yaml
- helm-charts/falcon-sensor/templates/serviceaccount.yaml
- helm-charts/falcon-sensor/values.yaml
- Set default minimum resource request for container sensor
- Add PSP for non-openshift clusters
- Provide serviceacocunt
> Various Updates

- Dockerfile
- Makefile
- PROJECT
- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/manager/controller_manager_config.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/kustomization.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_client_clusterrole.yaml
- config/rbac/auth_proxy_role.yaml
- config/rbac/auth_proxy_role_binding.yaml
- config/rbac/auth_proxy_service.yaml
- config/rbac/kustomization.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- config/rbac/service_account.yaml
- config/samples/crowdstrike_v1alpha1_falconsensor.yaml
- config/scorecard/kustomization.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
- watches.yaml
- Update to operator-sdk 1.10.1
- Namespace should use 'operator' in the name
- Add Falcon Container
> Update Helm operator

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/configmap.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.yaml
- Allow injector port to be configured
- Remove update KubeVersion limit in Chart.yaml
- Add RollingUpdate maxUnavailable configuration
> Add additional configuration options

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
- Update to validate container sensor configuration
> Update values schema

- README.md
- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/questions.yaml
- helm-charts/falcon-sensor/templates/NOTES.txt
- helm-charts/falcon-sensor/values.yaml
> Update docs and remove some outdated cli options

- README.md
Resolves a broken link on the README.md.
> Fix Helm Chart 404

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_psp.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
- Add some minor fixes around validation and kube version handling for PSP
- Fixes #100
> Add ability to pass registry json and some fixes

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/container_secret.yaml
- helm-charts/falcon-sensor/templates/container_webhook_upgrade.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
- Lookup all namespaces if enabled to add secrets to all namespaces
- Lookup existing certs and use if certification rotation is disabled
- Fixes #108
> Add lookup functions to handle advanced use cases

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
Adding some documentation and examples around some options (as requested by a few users)
> Add some additional examples into README

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/questions.yaml
updated confusing falconctl parameter to hopefully make more sense, and make it inline with our falcon docs.
> Updated to reflect appropriate values + verbiage

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/container_webhook_upgrade.yaml
- helm-charts/falcon-sensor/templates/node_psp.yaml
Closes #130 
I think this PR depends on PR #128 result. I would wait before merging it.
> fix: kubeversion minor cast to int for cloud distros

- helm-charts/falcon-integration-gateway/Chart.yaml
- helm-charts/falcon-integration-gateway/README.md
- Add instructions to install from helm repo
> Update install instructions

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
I'm fairly certain message_log is an unusable option.
> fix: docs. fix imagepullpolicy

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
- helm-charts/falcon-sensor/templates/_helpers.tpl
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
- helm-charts/falcon-sensor/templates/node_cleanup.yaml
- helm-charts/falcon-sensor/values.schema.json
- helm-charts/falcon-sensor/values.yaml
- Update docs to recommend digest over tags for security and production
> Allow use of digest for images

- helm-charts/falcon-integration-gateway/Chart.yaml
- helm-charts/falcon-integration-gateway/README.md
- helm-charts/falcon-integration-gateway/templates/_helpers.tpl
- helm-charts/falcon-integration-gateway/templates/secret.yaml
- helm-charts/falcon-integration-gateway/values.schema.json
- helm-charts/falcon-integration-gateway/values.yaml
Changes for the upcoming cloudtrail_lake FIG backend.
**MERGE CLOSER TO DEADLINE**
> Cloudtrail backend fig addition

- helm-charts/cs-k8s-protection-agent/Chart.yaml
- helm-charts/cs-k8s-protection-agent/README.md
@cs-pvyas 
Please review. Our console docs guide users through the console set up after cloud account registration so we'll probably want to adjust the install agent section. I included some of the extra info around the agent: proxy and resource consumption.
> kweishaar: add readme for KPA docs

- helm-charts/falcon-integration-gateway/Chart.yaml
- helm-charts/falcon-integration-gateway/README.md
- helm-charts/falcon-integration-gateway/templates/configmap.yaml
- helm-charts/falcon-integration-gateway/templates/secret.yaml
- helm-charts/falcon-integration-gateway/values.schema.json
- helm-charts/falcon-integration-gateway/values.yaml
This pull request presents multiple updates and enhancements for the Falcon Integration Gateway Helm chart:
1. **Updated Chart and App Version**: The Chart version has been incremented from 0.2.0 to 0.3.0, reflecting the updates made to the Helm chart. The App version has been incremented from 3.1.0 to 3.1.10, denoting that the application has undergone changes or improvements.
2. **Improved README Structure**: The README has been restructured for better readability and clarity. Headers such as "Dependencies" and "Configuration Options" have been promoted to higher levels, and additional information about installation and pre-requisites has been added.
3. **Configurable Exclusion of Events**: The `detections_exclude_clouds` configuration option has been added to the ConfigMap, allowing …
> Enhanced Falcon Integration Gateway Helm Chart

- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/README.md
Updated readme for falcon-kac to make it more clear
> Update README for falcon-kac install

- helm-charts/cs-k8s-protection-agent/Chart.yaml
- helm-charts/cs-k8s-protection-agent/README.md
- helm-charts/cs-k8s-protection-agent/ci/test-values.yaml
- helm-charts/cs-k8s-protection-agent/templates/_helpers.tpl
- helm-charts/cs-k8s-protection-agent/templates/cluster-role-read-access.yaml
- helm-charts/cs-k8s-protection-agent/templates/configmap.yaml
- helm-charts/cs-k8s-protection-agent/templates/deployment.yaml
- helm-charts/cs-k8s-protection-agent/templates/secret.yaml
- helm-charts/cs-k8s-protection-agent/values.schema.json
- helm-charts/cs-k8s-protection-agent/values.yaml
- Update helpers to have the latest fixes
- Fix cluster role to follow proper yaml notation
- Move required fields to values.schema.json
- Remove some whitespacing
- Bump version
- Add priorityClassName field to deployment
- add values.schema.json
> kpa: Several enhancements and fixes

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/README.md
> Fixed typo in README.md

- helm-charts/cs-k8s-protection-agent/Chart.yaml
- helm-charts/cs-k8s-protection-agent/templates/deployment.yaml
- helm-charts/cs-k8s-protection-agent/templates/docker-secret.yaml
- helm-charts/cs-k8s-protection-agent/values.yaml
- Support named pull secrets (--set image.pullSecrets)
- Base64 encoded secrets (--set image.registryConfigJSON)
> Add KPA custom pullSecrets support

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/_helpers.tpl
> fix: daemonset resource template mapping

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/README.md
- helm-charts/falcon-image-analyzer/templates/_helpers.tpl
- helm-charts/falcon-image-analyzer/templates/configmap.yaml
- helm-charts/falcon-image-analyzer/values.schema.json
- helm-charts/falcon-image-analyzer/values.yaml
- Drop use of agentRunmode variable
- Provide examples of use IAM OIDC roles
- Add variable to pass namespace and secret names for private registry access
> CS falcon iar helm updates

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/README.md
falcon-image-analyzer update Readme
> falcon-image-analyzer update Readme

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/node_priorityclass.yaml
> fix: priorityclass logic now that it is disabled by default

- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/templates/deployment_webhook.yaml
Increasing webhook timeout to 10 seconds to allow more time for ImageAssessment
> Increase KAC webhook timeout to 10 seconds

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/README.md
- helm-charts/falcon-image-analyzer/templates/_helpers.tpl
- helm-charts/falcon-image-analyzer/templates/configmap.yaml
- helm-charts/falcon-image-analyzer/values.yaml
falcon-image-analyzer add exclusions and update readme
> falcon-image-analyzer add exclusions and update readme

- helm-charts/cs-k8s-protection-agent/Chart.yaml
- helm-charts/cs-k8s-protection-agent/templates/deployment.yaml
- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/templates/daemonset.yaml
- helm-charts/falcon-image-analyzer/templates/deployment.yaml
> Fix priority class helm

- helm-charts/falcon-sensor/Chart.yaml
- helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
- helm-charts/falcon-sensor/values.yaml
Fix for resource settings configured in values.yaml for falcon sensor injector pod not being added to injector pod spec
> fix for resource settings for falcon sensor injector pod

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/values.schema.json
fixing the validation to check the ```daemonset.enabled=true``` OR ```deployment.enabled=true```
> validation bug fix

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/README.md
- helm-charts/falcon-image-analyzer/templates/configmap.yaml
- helm-charts/falcon-image-analyzer/values.yaml
add log.output field in values
> add log.output field in values

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/README.md
- helm-charts/falcon-image-analyzer/templates/_helpers.tpl
- helm-charts/falcon-image-analyzer/templates/configmap.yaml
- helm-charts/falcon-image-analyzer/values.yaml
> 1.1.8 helm version new

- artifacthub-repo.yml
- helm-charts/falcon-kac/Chart.yaml
- helm-charts/falcon-kac/README.md
- helm-charts/falcon-kac/templates/_helpers.tpl
- helm-charts/falcon-kac/templates/deployment_webhook.yaml
- helm-charts/falcon-kac/values.yaml
- updates resource requests and limits for falcon-kac
- update docs to reflect new visibility functionality
- remove release candidates from artifactory.io
> feat: update resource requests/limits, docs, and ignore release candidates

- helm-charts/falcon-image-analyzer/Chart.yaml
- helm-charts/falcon-image-analyzer/templates/daemonset.yaml
- helm-charts/falcon-image-analyzer/templates/deployment.yaml
v1.1.12 fix the google images for Gcp with image that has both amd and arm
> v1.1.12 fix the google images for Gcp with image that has both amd and arm

- helm-charts/falcon-sensor/templates/clusterrole.yaml
- helm-charts/falcon-sensor/templates/daemonset.yaml
To be included with the v1.31.0 release.
> New: Add cluster-config-id to sensor init container

- helm-charts/falcon-self-hosted-registry-assessment/Chart.yaml
- helm-charts/falcon-self-hosted-registry-assessment/README.md
- helm-charts/falcon-self-hosted-registry-assessment/templates/executor-deployment.yaml
- helm-charts/falcon-self-hosted-registry-assessment/values.yaml
Merge on March 17
Self Hosted Registry Assessment 1.4.0
Watch for official release notes through normal CrowdStrike channels.
> SHRA 1.4.0 release

- helm-charts/falcon-image-analyzer/Chart.yaml
> v1.1.14 updating app version
